version: '3.0'
services:
  hexagonal-app:
    container_name: hexagonal-app
    image: hexagonal-app
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./server/hexagonal-app:/hexagonal-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - hexagonal-network
    restart: unless-stopped

  db:
    container_name: db
    image: db
    build:
      context: db/
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - hexagonal-network
    restart: unless-stopped

  flyway:
    container_name: flyway
    build:
      context: flyway/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./server/hexagonal-app/src/main/resources/db/migration:/flyway/sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FLYWAY_BASELINE_ON_MIGRATE=${FLYWAY_BASELINE_ON_MIGRATE}
      - FLYWAY_BASELINE_VERSION=${FLYWAY_BASELINE_VERSION}
    networks:
      - hexagonal-network

networks:
  hexagonal-network:

volumes:
  db-volume:
    driver_opts:
      type: volume
      o: 'bind'
      device: '$HOME/data'